# Configuración global
defaultContentLanguage = 'es'

[languages]
  # --- Configuración para Español ---
  [languages.es]
    languageName = 'ES'
    weight = 1
    title = "Aldo Moreno"

    [languages.es.params]
      baseURL = "https://www.aldomoreno.net//"
      title = "Aldo Moreno"
      author = "Aldo Moreno"
      description = "QA Specialist y Bug Bounty Hunter"
      profilePicture = "images/perfil.jpg"
      favicon = "favicons/"
      disableArchiveTitleStyling  = true
      readMore = true

    # Menú en Español
    [[languages.es.menu.main]]
      name = "Inicio"
      identifier = "home"
      url = "/"
      weight = 100
    [[languages.es.menu.main]]
      name = "Archivo"
      url = "/posts/"
      weight = 200
    [[languages.es.menu.main]]
      name = "Logros"
      url = "/awards/"
      weight = 300

# --- Configuración para Inglés ---
  [languages.en]
    languageName = 'EN'
    weight = 2
    title = "Aldo Moreno"

    [languages.en.params]
      baseURL = "https://www.aldomoreno.net//"
      title = "Aldo Moreno"
      author = "Aldo Moreno"
      description = "QA Specialist and Bug Bounty Hunter"
      profilePicture = "images/perfil.jpg"
      favicon = "favicons/"
      disableArchiveTitleStyling  = true
      readMore = true

    # Menú en Inglés
    [[languages.en.menu.main]]
      name = "Home"
      identifier = "home"
      url = "/en/"
      weight = 100
    [[languages.en.menu.main]]
      name = "Archive"
      url = "/en/posts/"
      weight = 200
    [[languages.en.menu.main]]
      name = "Achievements"
      url = "/en/awards/"
      weight = 300


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"

[[params.socialIcons]]
icon = "fa-brands fa-linkedin-in"
title = "Linkedin"
url = "https://www.linkedin.com/in/jose-aldo-moreno-leon/"

[[params.socialIcons]]
icon = "fa-brands fa-x-twitter"
title = "X"
url = "https://x.com/aldo_m_leon"

[[params.socialIcons]]
icon = "fa-brands fa-github"
title = "Github"
url = "https://github.com/aldo-moreno-leon"

[[params.socialIcons]]
icon = "fa-solid fa-envelope"
title = "e-mail"
url = "mailto:aldo.moreno.leon@protonmail.com"

[[params.socialIcons]]
icon = "fa-solid fa-b"
title = "Bugcrowd"
url = "https://bugcrowd.com/h/aldo_m_leon"